/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal;

import java.io.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.*;

/**
 *
 * @author kshitij
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    byte[] person_image=new byte[9999];
    
    public static String name,gender,weight,nationality,height,hair,eye;
    
    public Add() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(395, 295));
        jPanel1.setLayout(null);

        jButton1.setText("Add photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 10, 110, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("WEIGHT(kg)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 90, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("HEIGHT(cm)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("GENDER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 50, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("NATIONALITY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("HAIR COLOR");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("EYE COLOR");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 230, 80, 15);

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(102, 255, 102));
        jCheckBox1.setText("Human Trafficking");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(20, 360, 130, 23);

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setForeground(new java.awt.Color(102, 255, 102));
        jCheckBox4.setText("Child Abusement");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(20, 400, 130, 23);

        jCheckBox5.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setForeground(new java.awt.Color(102, 255, 102));
        jCheckBox5.setText("Drug Dealing");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(170, 400, 100, 23);

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setForeground(new java.awt.Color(102, 255, 102));
        jCheckBox2.setText("Extortion");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(170, 360, 100, 23);

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setForeground(new java.awt.Color(102, 255, 102));
        jCheckBox3.setText("Bomb Blast");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(310, 360, 90, 23);

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 50, 130, 20);

        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 80, 130, 20);

        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(100, 110, 130, 20);

        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(100, 140, 130, 20);

        jTextField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(100, 170, 130, 20);

        jTextField6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(100, 200, 130, 20);

        jTextField7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField7);
        jTextField7.setBounds(100, 230, 130, 20);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(248, 30, 0));
        jButton2.setText("Criminalize Now");
        jButton2.setToolTipText("Submit");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 430, 130, 23);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 50, 250, 300);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CRIMES COMMITTED");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 290, 190, 50);

        jButton3.setText("BACK TO HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 10, 130, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        try {
           
            JFileChooser chooser=new JFileChooser();
                chooser.showOpenDialog(null);
        
                File f=chooser.getSelectedFile();
                String fname=f.getAbsolutePath();
                File image=new File(fname);
                FileInputStream fis =new FileInputStream(image);
                ByteArrayOutputStream bos=new ByteArrayOutputStream();
                byte[] buff=new byte[1024];
                for(int i;(i=fis.read(buff))!=-1;)
                {
                bos.write(buff,0,i);
                }
                person_image =bos.toByteArray();
               
              byte[] data=person_image;
                format=new ImageIcon(data);
                jLabel8.setIcon(format);
        } catch (Exception ex) {
            System.out.println(""+ex);
        }
              
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        name=jTextField1.getText();
        weight=jTextField2.getText();
        height=jTextField3.getText();
        gender=jTextField4.getText();
        nationality=jTextField5.getText();
        hair=jTextField6.getText();
        eye=jTextField7.getText();
        
            if("".equals(name) || "".equals(gender) ||"".equals(height) || "".equals(nationality) || "".equals(weight))
        {
            JOptionPane.showMessageDialog(this,"Plzz fill all the details");
            
        }   
            else if(jCheckBox1.isSelected()||jCheckBox4.isSelected()||jCheckBox5.isSelected()||jCheckBox2.isSelected()||jCheckBox3.isSelected()){
                Date dNow = new Date();
                SimpleDateFormat ft = new SimpleDateFormat("ddhhmmss");
                String datetime = ft.format(dNow);
                System.out.println(""+datetime);
               
                DBConnect db1=new DBConnect();
                int x=Integer.parseInt(datetime);
              
                try{
                     if(!(gender.length()==1 && (gender.contains("m") || gender.contains("M") || gender.contains("f") || gender.contains("F")))){
                   jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText("");jTextField5.setText("");jTextField6.setText("");jTextField7.setText("");
                         throw new Exceptionown("enter gender: m/f");
              }
                            PreparedStatement ps=db1.getConnection().prepareStatement("insert into criminal values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setInt(1, x);
                    ps.setString(2, name);
                    
                    ps.setString(3, gender);
                    ps.setString(4, weight);
                    ps.setString(5, nationality);
                    ps.setString(6, height);
               
                    
                    ps.setString(7, hair);
                    ps.setString(8, eye);
                  
                   
                    
                  if (jCheckBox1.isSelected())
                  { 
                      System.out.println("check");
                      ps.setString(9,jCheckBox1.getText());
                  }
                  else
                  {
                      ps.setString(9,"");
                  }
                           if (jCheckBox2.isSelected())
                  {
                      ps.setString(10,jCheckBox2.getText());
                  }
                           else
                  {
                      ps.setString(10,"");
                  }
                           if (jCheckBox3.isSelected())
                  {
                      ps.setString(11,jCheckBox3.getText());
                  }
                           else
                  {
                      ps.setString(11,"");
                  }
                           if (jCheckBox4.isSelected())
                  {
                      ps.setString(12,jCheckBox4.getText());
                  }
                           else
                  {
                      ps.setString(12,"");
                  }
                           if (jCheckBox5.isSelected())
                  {
                      ps.setString(13,jCheckBox5.getText());
                  }
                           else
                  {
                      ps.setString(13,"");
                  }
                    ps.setBytes(14, person_image);
                    
                    ps.executeUpdate();
                 JOptionPane.showMessageDialog(this,"Criminal has been added to database");
                 new view().setVisible(true);
                 this.setVisible(false);
                }
                catch(Exception e){System.out.println(""+e);
                }
                }
           else{
               JOptionPane.showMessageDialog(this,"Criminal must have committed a crime...");
           }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
  new home().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }
    private ImageIcon format=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
